name: Telegram TA Signal

on:
  schedule:
  - cron: '10 10 * * 0-4'  # Runs at 3:55 PM NPT, Sunday to Thursday

  workflow_dispatch:

jobs:
  send-ta-alert:
    runs-on: ubuntu-latest

    env:
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
      GOOGLE_AUTH: ${{ secrets.GOOGLE_AUTH }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Telegram TA signal script
        run: python ta_to_telegram.py
