name: Telegram TA Signal

on:
  schedule:
    - cron: '35 9 * * 0-4'  # Runs at 3:20 PM NPT (UTC+5:45), Sunday to Thursday
  workflow_dispatch:

jobs:
  send-ta-alert:
    runs-on: ubuntu-latest

    env:
      telegram_bot_token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      channel_id: ${{ secrets.TELEGRAM_CHANNEL_ID }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Telegram TA signal script
        run: python ta_to_telegram.py
